# Generated by Django 5.0.2 on 2024-02-13 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_delete_menuitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Menu",
        ),
    ]
