# Generated by Django 5.0.2 on 2024-02-13 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_menu_menuitem_menu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="parent",
            new_name="parent_item",
        ),
    ]
