# Generated by Django 5.0.2 on 2024-02-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_rename_parent_menuitem_parent_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="url",
            field=models.URLField(blank="True", max_length=100, null=True),
        ),
    ]
