# Generated by Django 5.0.2 on 2024-02-13 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_menuitem_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="url",
            new_name="path",
        ),
    ]
