# Generated by Django 5.0.2 on 2024-02-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_url_menuitem_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="path",
            field=models.CharField(blank="True", max_length=100, null=True),
        ),
    ]
