# Generated by Django 5.0.2 on 2024-02-14 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_menuitem_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="parent_item",
            new_name="parent",
        ),
    ]
